spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activiti5?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver